### ISSUE TITLE
Status of Teensy MassStorageDriver?

### ISSUE THREAD

**Issue by lukehutch** [WMXZ-EU/uSDFS#13]
I found this 2019 thread:

https://forum.pjrc.com/threads/55821-USBHost_t36-USB-Mass-Storage-Driver-Experiments

As far as I can tell, this is the work that became the MassStorageDriver.cpp code in the USBHost_t36 library. Is that correct?

That code does not include a FAT filesystem. From the above thread, it sounds like I need the ELM-Chan FatFS library for that.

However, I'm not sure how to link that library with MassStorageDriver. The code in the uSDFS GitHub repo seems to be targeted at reading an SD card, and I assume it's based on a version of the mass storage code from before MassStorageDriver.cpp was incorporated into USBHost_t36.

What are the right steps needed to be able to read FAT drives on Teensy 4.1, using USBHost_t36?

Thanks!

**Comment by WMXZ-EU** [comment]
Originally wwatson was using this library to implement MSC of USB_Host. 
uSDFS is the ELM-CHanN FatFS and it has in utility also the interface into MSC.
In the past, we tested the system on a variety of USB devices and SD cards etc.

Meanwhile, wwatson moved on to add Bill Greimann's SdFat-V2. I had no time to follow this development, so I suggest to follow wwatson forum entries.
